### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ryanwjackson**
Update readme based on feedback in #31

### CODE REVIEW

**Comment by shonski69** [comment]
I not sure what to do from her please help

**Comment by amouxkin** [comment]
> 

 @shonski69 Could you explain where exactly you're having problems ?

**Comment by shonski69** [comment]
> > 
> 
>  @shonski69 Could you explain where exactly you're having problems ?

I don't know what I'm doing I hope I didn't screw things up

**Comment by shonski69** [comment]
> > 
> 
>  @shonski69 Could you explain where exactly you're having problems ?

How do I transfer ledger to fund in bank accont

**Pull request merged**
